apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
  namespace: wago
  labels:
    app:
      server
spec:
  replicas: 5
  serviceName: server
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          args:
            - --grpc-port=8080
            - --cluster=http://server-0:9020,http://server-1:9020,http://server-2:9020,http://server-3:9020,http://server-4:9020
            - --join
          image: arlyon/wago:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer